# Generated by Django 4.2.7 on 2023-11-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadena', models.CharField(max_length=50, verbose_name='Cadena')),
                ('anio', models.CharField(max_length=50, verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
        ),
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloCapitulo', models.CharField(max_length=255, verbose_name='Título')),
                ('numeroActor', models.CharField(max_length=50)),
                ('personaje', models.CharField(max_length=255, verbose_name='Personaje')),
                ('nombreActor', models.CharField(max_length=255, verbose_name='NombreActor')),
                ('numeroObra', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('explotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repertorio_explotacion', to='publicacion.explotacion')),
            ],
        ),
        migrations.AddField(
            model_name='explotacion',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explotacion_serie', to='publicacion.serie'),
        ),
    ]
